fix docker stuff

diff --git a/.github/workflows/docker-server-build-run.yaml b/.github/workflows/docker-server-build-run.yaml
--- a/.github/workflows/docker-server-build-run.yaml
+++ b/.github/workflows/docker-server-build-run.yaml
@@ -1,4 +1,4 @@
-name: Docker Server Test
+name: Docker Server Build and Run
 
 on:
   push:
@@ -34,11 +34,20 @@ jobs:
 
       - name: Check server health
         run: |
-          echo "Attempting to connect to server..."
+          echo "Attempting to connect to dashboard..."
           curl -v http://localhost:8101
           response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8101)
           echo "Response code: $response_code"
           if [ $response_code -ne 200 ]; then
             echo "Server health check failed with status code: $response_code"
+            exit 1
+          fi
+          
+          echo "Attempting to connect to backend..."
+          curl -v http://localhost:8102
+          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8102)
+          echo "Response code: $response_code"
+          if [ $response_code -ne 200 ]; then
+            echo "Backend health check failed with status code: $response_code"
             exit 1
           fi
